# Generated by Django 2.2.4 on 2020-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200525_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_de_creacion'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado/No destacado'),
        ),
    ]
