# Generated by Django 2.2.4 on 2020-07-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200616_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
